language: java

jdk:
    - oraclejdk8

services:
    - mysql

before_install:
    - mysql -uroot -e "grant all on belajar.* to test@localhost identified by 'password'"
    - mysql -uroot -e "drop database if exists belajar"
    - mysql -uroot -e "create database belajar"

after_success:
    - mvn jacoco:report coveralls:report